name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Authenticate to docker
      run: echo $DOCKER_API_KEY | docker login --username mwangithegreat --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mwangithegreat/mailhog:latest
    - name: Push the image to Docker
      run: docker push mwangithegreat/mailhog
